apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: YWRtaW46cmVkaGF0MWFkbWluIQp1c2VyMTpyZWRoYXQxIQp1c2VyMjpyZWRoYXQxIQp1c2VyMzpyZWRoYXQxIQp1c2VyNDpyZWRoYXQxIQp1c2VyNTpyZWRoYXQxIQo=
